# Generated by Django 3.2 on 2021-09-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
