# Generated by Django 3.2 on 2021-09-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210910_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk']},
        ),
    ]
