# Generated by Django 3.2 on 2021-09-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210906_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, to='mainapp.article'),
        ),
    ]
